- name: install mongodb
  hosts: mongodb
  become: yes
  tasks:
  - name: install mongodb repo
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo
  - name: install mongodb
    ansible.builtin.yum:
      name: mongodb-org
      state: installed
  - name: started mongodb
    ansible.builtin.service:
      name: mongod
      state: started
      enabled: yes
  - name: remote enable
    ansible.builtin.replace:
      regexp: '127.0.0.1'
      replace: '0.0.0.0'
  - name: restart mongodb
    ansible.builtin.service:
      name: mongod
      state: restarted
